const defaultCostCodes = [
    { "code": "1001", "trade": "General Contractor" },
    { "code": "1002", "trade": "General Contractor - Airports" },
    { "code": "1003", "trade": "General Contractor - Churches" },
    { "code": "1004", "trade": "General Contractor - Commercial" },
    { "code": "1005", "trade": "General Contractor - Project General Requirements" },
    { "code": "1006", "trade": "General Contractor - Heavy/Highway" },
    { "code": "1007", "trade": "General Contractor - Industrial Maintenance" },
    { "code": "1008", "trade": "General Contractor - Industrial" },
    { "code": "1009", "trade": "General Contractor - Institutional" },
    { "code": "1010", "trade": "General Contractor - Pre Engineered Buildings" },
    { "code": "1011", "trade": "General Contractor - High Rise Office" },
    { "code": "1012", "trade": "General Contractor - Low Rise Office" },
    { "code": "1013", "trade": "General Contractor - High Rise Apartments" },
    { "code": "1014", "trade": "General Contractor - Low Rise Apartments" },
    { "code": "1015", "trade": "General Contractor - Waste Water Treatment" },
    { "code": "1016", "trade": "General Contractor - Construction Manager" },
    { "code": "1017", "trade": "General Contractor - Facilities Manager" },
    { "code": "1018", "trade": "General Contractor - Historical Renovation" },
    { "code": "1019", "trade": "General Contractor - Tenant Finish" },
    { "code": "1021", "trade": "General Contractor - Interior Finish" },
    { "code": "1024", "trade": "General Contractor - Farm Buildings" },
    { "code": "1025", "trade": "General Contractor - Health Care Facilities/Services" },
    { "code": "1026", "trade": "General Contractor - Hangar & Maintenance" },
    { "code": "1030", "trade": "General Contractor - Industrial & Commercial" },
    { "code": "1031", "trade": "General Contractor - Custom Built Homes" },
    { "code": "1032", "trade": "General Contractor - Residential Multi Family" },
    { "code": "1033", "trade": "General Contractor - Retail" },
    { "code": "1040", "trade": "General Contractor - Other Specialty Construction" },
    { "code": "1060", "trade": "Construction Management/Coordination Firm" },
    { "code": "1310", "trade": "Project Scheduling" },
    { "code": "1330", "trade": "Engineering Services" },
    { "code": "1380", "trade": "Construction Documentation" },
    { "code": "1400", "trade": "Quality Control Services" },
    { "code": "1500", "trade": "Temporary Facilities" },
    { "code": "1505", "trade": "Portable Toilets" },
    { "code": "1510", "trade": "Temporary Utilities" },
    { "code": "1520", "trade": "Security Services" },
    { "code": "1525", "trade": "Construction Aids" },
    { "code": "1560", "trade": "Temporary Controls" },
    { "code": "1580", "trade": "Project Identification and Signs" },
    { "code": "1600", "trade": "Construction Equipment" },
    { "code": "1630", "trade": "Construction Tools" },
    { "code": "1710", "trade": "Construction Cleaning Services" },
    { "code": "1905", "trade": "Insurance and Bonding" },
    { "code": "2010", "trade": "Site Work Supplier" },
    { "code": "2015", "trade": "Grade Staking" },
    { "code": "2040", "trade": "Aggregate Manufacture Supplier" },
    { "code": "2050", "trade": "Demolition" },
    { "code": "2055", "trade": "Hazardous Material Removal" },
    { "code": "2060", "trade": "Off-site Transportation and Disposal" },
    { "code": "2065", "trade": "Cement" },
    { "code": "2100", "trade": "Site Preparation" },
    { "code": "2105", "trade": "Earthwork Supplies" },
    { "code": "2107", "trade": "Geosynthetics" },
    { "code": "2140", "trade": "Dewatering" },
    { "code": "2150", "trade": "Excavation Support & Shoring Systems" },
    { "code": "2200", "trade": "Earthwork" },
    { "code": "2240", "trade": "Soil Stabilization" },
    { "code": "2280", "trade": "Soil Treatment" },
    { "code": "2300", "trade": "Tunneling" },
    { "code": "2315", "trade": "Man Hole Covers" },
    { "code": "2350", "trade": "Piling" },
    { "code": "2380", "trade": "Caissons/Drilled Piers" },
    { "code": "2400", "trade": "Underground Utilities" },
    { "code": "2450", "trade": "Railroad Work" },
    { "code": "2480", "trade": "Marine Work" },
    { "code": "2485", "trade": "Marine Diving" },
    { "code": "2510", "trade": "Asphalt Paving" },
    { "code": "2513", "trade": "Asphalt Paving Concrete Materials" },
    { "code": "2515", "trade": "Unit Pavers" },
    { "code": "2516", "trade": "Base Courses" },
    { "code": "2520", "trade": "Concrete Paving" },
    { "code": "2525", "trade": "Curbs" },
    { "code": "2530", "trade": "Athletic Paving & Surfacing" },
    { "code": "2570", "trade": "Site Concrete" },
    { "code": "2580", "trade": "Pavement Marking" },
    { "code": "2600", "trade": "Site Utilities Pressure Piping" },
    { "code": "2670", "trade": "Water Wells" },
    { "code": "2700", "trade": "Sewerage and Drainage" },
    { "code": "2710", "trade": "Septic Systems" },
    { "code": "2760", "trade": "Restoration of Underground Pipelines" },
    { "code": "2770", "trade": "Ponds and Reservoirs" },
    { "code": "2800", "trade": "Site Improvements" },
    { "code": "2830", "trade": "Fences & Gates" },
    { "code": "2900", "trade": "Landscaping and Irrigation" },
    { "code": "3010", "trade": "Concrete Contractor" },
    { "code": "3050", "trade": "Concrete Supplier" },
    { "code": "3100", "trade": "Concrete Formwork" },
    { "code": "3200", "trade": "Concrete Reinforcing" },
    { "code": "3210", "trade": "Reinforcing Steel" },
    { "code": "3300", "trade": "Cast In Place Concrete" },
    { "code": "3310", "trade": "Cement Supplier" },
    { "code": "3320", "trade": "Ready-Mix Concrete" },
    { "code": "3345", "trade": "Concrete Placing and Finishing" },
    { "code": "3346", "trade": "Concrete Curling Supplier" },
    { "code": "3347", "trade": "Grout" },
    { "code": "3350", "trade": "Special Finish Concrete" },
    { "code": "3360", "trade": "Specially Placed Concrete" },
    { "code": "3400", "trade": "Precast Concrete" },
    { "code": "3460", "trade": "Site Cast Precast Concrete" },
    { "code": "3480", "trade": "Precast Concrete Specialties" },
    { "code": "3500", "trade": "Cementitious Decks" },
    { "code": "3510", "trade": "Gypsum Concrete" },
    { "code": "3540", "trade": "Concrete Sealer" },
    { "code": "3700", "trade": "Concrete Restoration and Cleaning" },
    { "code": "4200", "trade": "Masonry" },
    { "code": "4331", "trade": "Brick Masonry Supplies" },
    { "code": "4332", "trade": "Mortar & Masonry Grout" },
    { "code": "4333", "trade": "Reinforced Unit Masonry" },
    { "code": "4336", "trade": "Washed Sand & Gravel" },
    { "code": "4400", "trade": "Stone" },
    { "code": "4500", "trade": "Masonry Restoration and Cleaning" },
    { "code": "4550", "trade": "Special Masonry Installations" },
    { "code": "5010", "trade": "Structural Metal Erection" },
    { "code": "5050", "trade": "Basic Metal Materials and Methods" },
    { "code": "5100", "trade": "Structural Framing" },
    { "code": "5105", "trade": "Millwright" },
    { "code": "5110", "trade": "Rigging" },
    { "code": "5120", "trade": "Structural Steel" },
    { "code": "5210", "trade": "Steel Joists" },
    { "code": "5300", "trade": "Metal Decking" },
    { "code": "5400", "trade": "Cold Formed Metal Framing" },
    { "code": "5410", "trade": "Load Bearing Metal Studs" },
    { "code": "5500", "trade": "Miscellaneous Metal Fabrications" },
    { "code": "5520", "trade": "Metal Handrails & Railings" },
    { "code": "5535", "trade": "Gratings and Floor Plates" },
    { "code": "5560", "trade": "Metal Castings" },
    { "code": "5700", "trade": "Ornamental Metal" },
    { "code": "5800", "trade": "Expansion Control" },
    { "code": "5900", "trade": "Metal Restoration and Cleaning" },
    { "code": "6090", "trade": "Wood And Plastic Fastenings" },
    { "code": "6100", "trade": "Rough Carpentry" },
    { "code": "6130", "trade": "Structural Wood Components" },
    { "code": "6170", "trade": "Roof Structure" },
    { "code": "6200", "trade": "Finish Carpentry/Architectural Woodwork" },
    { "code": "6220", "trade": "Millwork" },
    { "code": "6300", "trade": "Lumber" },
    { "code": "6415", "trade": "Countertops" },
    { "code": "6600", "trade": "Plastic Fabrications" },
    { "code": "6900", "trade": "Wood and Plastic Restoration and Cleaning" },
    { "code": "7100", "trade": "Waterproofing/Dampproofing" },
    { "code": "7200", "trade": "Insulation" },
    { "code": "7240", "trade": "Exterior Insulation and Finish Systems" },
    { "code": "7250", "trade": "Fireproofing" },
    { "code": "7310", "trade": "Shingles" },
    { "code": "7320", "trade": "Roofing Tiles" },
    { "code": "7400", "trade": "Preformed Roofing and Cladding/Siding" },
    { "code": "7405", "trade": "Roofing Supplier" },
    { "code": "7500", "trade": "Membrane Roofing and Sheet Metal" },
    { "code": "7510", "trade": "Built-Up Roofing" },
    { "code": "7620", "trade": "Sheet Metal Flashing" },
    { "code": "7700", "trade": "Roof Specialties" },
    { "code": "7800", "trade": "Skylights" },
    { "code": "7840", "trade": "Firestopping" },
    { "code": "7900", "trade": "Joint Sealers" },
    { "code": "8100", "trade": "Metal Doors and Frames" },
    { "code": "8110", "trade": "Man Doors, Frames and Hardware" },
    { "code": "8120", "trade": "Special Metal Doors and Frames" },
    { "code": "8200", "trade": "Wood and Plastic Doors" },
    { "code": "8300", "trade": "Special Doors" },
    { "code": "8305", "trade": "Access Doors" },
    { "code": "8310", "trade": "Sliding Doors" },
    { "code": "8330", "trade": "Overhead and Coiling Doors" },
    { "code": "8350", "trade": "Folding Doors and Grilles" },
    { "code": "8400", "trade": "Entrances, Storefronts, Glazing and Curtain Wall" },
    { "code": "8500", "trade": "Metal Windows" },
    { "code": "8600", "trade": "Wood and Plastic Windows" },
    { "code": "8650", "trade": "Special Windows" },
    { "code": "8700", "trade": "Hardware" },
    { "code": "9050", "trade": "Basic Finish Materials And Methods" },
    { "code": "9120", "trade": "Ceiling Suspension" },
    { "code": "9200", "trade": "Lath and Plaster" },
    { "code": "9250", "trade": "Drywall" },
    { "code": "9300", "trade": "Tile and Terrazzo" },
    { "code": "9500", "trade": "Acoustical Treatment" },
    { "code": "9510", "trade": "Acoustical Ceiling" },
    { "code": "9540", "trade": "FRP" },
    { "code": "9550", "trade": "Wood Flooring" },
    { "code": "9600", "trade": "Stone & Masonry Flooring" },
    { "code": "9610", "trade": "Cultured Marble" },
    { "code": "9650", "trade": "Soft Flooring" },
    { "code": "9680", "trade": "Carpet" },
    { "code": "9700", "trade": "Special Flooring and Floor Treatment" },
    { "code": "9790", "trade": "Paint Removal" },
    { "code": "9800", "trade": "Special Coatings" },
    { "code": "9900", "trade": "Painting and Wall Coverings" },
    { "code": "9950", "trade": "Wall coverings" },
    { "code": "9980", "trade": "Sandblasting" },
    { "code": "10100", "trade": "Chalkboards and Tackboards" },
    { "code": "10150", "trade": "Compartments and Cubicles" },
{ "code": "10200", "trade": "Louvers, Vents and Screens" },
{ "code": "10260", "trade": "Wall and Corner Guards" },
{ "code": "10270", "trade": "Access Flooring" },
{ "code": "10280", "trade": "Specialty Modules" },
{ "code": "10300", "trade": "Fireplaces and Stoves" },
{ "code": "10340", "trade": "Prefabricated Exterior Specialties" },
{ "code": "10350", "trade": "Flagpoles" },
{ "code": "10400", "trade": "Identifying Devices" },
{ "code": "10450", "trade": "Pedestrian Control Devices" },
{ "code": "10500", "trade": "Lockers" },
{ "code": "10520", "trade": "Fire Protection Specialties" },
{ "code": "10530", "trade": "Protective Covers" },
{ "code": "10550", "trade": "Postal Specialties" },
{ "code": "10600", "trade": "Partitions" },
{ "code": "10650", "trade": "Operable Partitions" },
{ "code": "10670", "trade": "Storage Shelving" },
{ "code": "10700", "trade": "Exterior Sun Control Devices" },
{ "code": "10750", "trade": "Telephone Specialties" },
{ "code": "10800", "trade": "Toilet and Bath Accessories" },
{ "code": "10880", "trade": "Scales" },
{ "code": "10900", "trade": "Wardrobe and Closet Specialties" },
{ "code": "10950", "trade": "Miscellaneous Specialties" },
{ "code": "11010", "trade": "Maintenance Equipment" },
{ "code": "11020", "trade": "Bank, Security and Vault Equipment" },
{ "code": "11040", "trade": "Ecclesiastical Equipment" },
{ "code": "11050", "trade": "Library Equipment" },
{ "code": "11060", "trade": "Theater and Stage Equipment" },
{ "code": "11070", "trade": "Instrumental Equipment" },
{ "code": "11100", "trade": "Mercantile Equipment" },
{ "code": "11110", "trade": "Commercial Laundry and Dry Cleaning Equipment" },
{ "code": "11120", "trade": "Vending Equipment" },
{ "code": "11130", "trade": "Audio Visual Equipment" },
{ "code": "11140", "trade": "Service Station Equipment" },
{ "code": "11145", "trade": "Air Compressor" },
{ "code": "11150", "trade": "Parking Control Equipment" },
{ "code": "11160", "trade": "Loading Dock Equipment" },
{ "code": "11170", "trade": "Solid Waste Handling Equipment" },
{ "code": "11190", "trade": "Detention Equipment" },
{ "code": "11200", "trade": "Water Supply and Treatment Equipment" },
{ "code": "11280", "trade": "Dam, Hydroelectric, and Irrigation Project" },
{ "code": "11300", "trade": "Fluid Waste Treatment and Disposal Equipment" },
{ "code": "11400", "trade": "Food Service Equipment" },
{ "code": "11450", "trade": "Residential Equipment" },
{ "code": "11460", "trade": "Unit Kitchens" },
{ "code": "11470", "trade": "Darkroom Equipment" },
{ "code": "11480", "trade": "Athletic, Recreational and Therapeutic Equipment" },
{ "code": "11500", "trade": "Industrial and Process Equipment" },
{ "code": "11600", "trade": "Laboratory Equipment" },
{ "code": "11660", "trade": "Planetarium and Observatory Equipment" },
{ "code": "11700", "trade": "Medical Equipment" },
{ "code": "11780", "trade": "Mortuary Equipment" },
{ "code": "11850", "trade": "Navigation Equipment" },
{ "code": "11900", "trade": "Miscellaneous Specialty Equipment" },
{ "code": "12100", "trade": "Artwork" },
{ "code": "12300", "trade": "Manufactured Casework" },
{ "code": "12335", "trade": "Medical Casework" },
{ "code": "12390", "trade": "Residential Casework" },
{ "code": "12500", "trade": "Window Treatment" },
{ "code": "12610", "trade": "Landscape Partitions and Components" },
{ "code": "12620", "trade": "Furniture, Furniture Systems, and Furniture" },
{ "code": "12670", "trade": "Rugs and Mats" },
{ "code": "12700", "trade": "Multiple Seating" },
{ "code": "12750", "trade": "Systems Furniture" },
{ "code": "12800", "trade": "Interior Plants and Planters" },
{ "code": "13010", "trade": "Air Supported Structures" },
{ "code": "13020", "trade": "Integrated Assemblies" },
{ "code": "13030", "trade": "Special Purpose Rooms" },
{ "code": "13080", "trade": "Sound, Vibration, and Seismic Control" },
{ "code": "13090", "trade": "Radiation Protection" },
{ "code": "13100", "trade": "Nuclear Reactors" },
{ "code": "13120", "trade": "Pre Engineered Structures" },
{ "code": "13150", "trade": "Pools" },
{ "code": "13160", "trade": "Ice Rinks" },
{ "code": "13170", "trade": "Kennels and Animal Shelters" },
{ "code": "13180", "trade": "Site Constructed Incinerators" },
{ "code": "13200", "trade": "Liquid and Gas Storage Tanks" },
{ "code": "13230", "trade": "Digestion Tank Covers and Appurtenances" },
{ "code": "13240", "trade": "Oxygenation Systems" },
{ "code": "13260", "trade": "Sludge Conditioning Systems" },
{ "code": "13300", "trade": "Utility Control Systems" },
{ "code": "13400", "trade": "Industrial and Process Control Systems" },
{ "code": "13500", "trade": "Recording Instrumentation" },
{ "code": "13550", "trade": "Transportation Control Instrumentation" },
{ "code": "13600", "trade": "Solar Energy Systems" },
{ "code": "13700", "trade": "Wind Energy Systems" },
{ "code": "13800", "trade": "Building Automation Systems" },
{ "code": "13900", "trade": "Fire Suppression and Supervisory Systems" },
{ "code": "14100", "trade": "Dumbwaiters" },
{ "code": "14200", "trade": "Elevators" },
{ "code": "14300", "trade": "Moving Stairs and Walks" },
{ "code": "14400", "trade": "Lifts" },
{ "code": "14450", "trade": "Vehicle Lifts" },
{ "code": "14500", "trade": "Material Handling Systems" },
{ "code": "14560", "trade": "Chutes" },
{ "code": "14580", "trade": "Tube Systems" },
{ "code": "14600", "trade": "Hoists and Cranes" },
{ "code": "14700", "trade": "Turntables" },
{ "code": "14800", "trade": "Scaffolding" },
{ "code": "14900", "trade": "Transportation Systems" },
{ "code": "15050", "trade": "Basic Mechanical Materials And Methods" },
{ "code": "15230", "trade": "Industrial Process Piping" },
{ "code": "15250", "trade": "Mechanical Insulation" },
{ "code": "15300", "trade": "Fire Protection" },
{ "code": "15400", "trade": "Plumbing" },
{ "code": "15500", "trade": "Heating, Ventilating, and Air Conditioning (HVAC)" },
{ "code": "15510", "trade": "Heating Boilers And Accessories" },
{ "code": "15800", "trade": "Process Piping & Equipment" },
{ "code": "15950", "trade": "Controls" },
{ "code": "15990", "trade": "Testing, Adjusting, and Balancing" },
{ "code": "16050", "trade": "Basic Electrical Materials And Methods" },
{ "code": "16100", "trade": "Electrical Contractor" },
{ "code": "16300", "trade": "Site Electrical Distribution" },
{ "code": "16320", "trade": "High Voltage Distribution, Switching and Protection" },
{ "code": "16360", "trade": "Fire Monitor System" },
{ "code": "16400", "trade": "Industrial Electrical Work" },
{ "code": "16670", "trade": "Lightning Protection Systems" },
{ "code": "16700", "trade": "Communications" },
{ "code": "16750", "trade": "Alarm Systems" },
{ "code": "16800", "trade": "Fiber Optic Cabling" },
{ "code": "16900", "trade": "Controls" },
{ "code": "16950", "trade": "Testing" },
{ "code": "20100", "trade": "Accounting" },
{ "code": "20200", "trade": "Consulting" },
{ "code": "20300", "trade": "Attorney" },
{ "code": "20400", "trade": "Developer" },
{ "code": "20700", "trade": "Business Services" },
{ "code": "20800", "trade": "Insurance" },
{ "code": "20805", "trade": "Bonding" },
{ "code": "20810", "trade": "Banking" },
{ "code": "20900", "trade": "Supplier" },
{ "code": "203450", "trade": "Cement Based Underlayment" },
{ "code": "201000", "trade": "Construction Reports" },
{ "code": "201100", "trade": "Construction Employment Firm" },
{ "code": "201200", "trade": "Advertising" },
{ "code": "201300", "trade": "Internet Services" },
{ "code": "201400", "trade": "Timberline Software" },
{ "code": "201500", "trade": "Chapter Lobbyist" },
{ "code": "201600", "trade": "Environmental Services" },
{ "code": "201800", "trade": "Labor Staffing Services" },
{ "code": "202010", "trade": "Arborist" },
{ "code": "20202020", "trade": "Dumpster Service/Rolloff/Transfer Station" },
{ "code": "20202030", "trade": "Employee Benefits" },
{ "code": "20202040", "trade": "Financial Planning" },
{ "code": "20202050", "trade": "Prevailing Wage Benefit Plans" },
{ "code": "20202060", "trade": "Printing & Reproduction" },
{ "code": "20202070", "trade": "Online Planroom" },
{ "code": "20202080", "trade": "Automotive Dealership" },
{ "code": "20202090", "trade": "Safety Services" },
{ "code": "20202100", "trade": "Signs" },
{ "code": "21010", "trade": "Processing and Coordination" },
{ "code": "21020", "trade": "Architectural Design" },
{ "code": "21025", "trade": "Civil Engineering" },
{ "code": "21030", "trade": "Structural Engineering" },
{ "code": "21040", "trade": "Mechanical Engineering" },
{ "code": "21045", "trade": "Electrical Engineering" },
{ "code": "21050", "trade": "Landscape Architecture" },
{ "code": "21055", "trade": "Tests and Inspections" },
{ "code": "21060", "trade": "Plan Replication" },
{ "code": "21062", "trade": "Commissioning" },
{ "code": "21065", "trade": "Building Permits" },
{ "code": "21070", "trade": "Plan Check Fees" },
{ "code": "21080", "trade": "Planning Fees" },
{ "code": "21085", "trade": "School District Fees" },
{ "code": "21090", "trade": "Other Fees" },
{ "code": "22010", "trade": "General Contractor - Project Supervision" }

];
export default defaultCostCodes;